function si_test_Demo(){var H='bootstrap',I='begin',J='gwt.codesvr.si.test.Demo=',K='gwt.codesvr=',L='si.test.Demo',M='startup',N='DUMMY',O=0,P=1,Q='iframe',R='javascript:""',S='position:absolute; width:0; height:0; border:none; left: -1000px;',T=' top: -1000px;',U='CSS1Compat',V='<!doctype html>',W='',X='<html><head><\/head><body><\/body><\/html>',Y='undefined',Z='DOMContentLoaded',$=50,_='script',ab='javascript',bb='si_test_Demo',cb='Failed to load ',db='moduleStartup',eb='scriptTagAdded',fb='moduleRequested',gb='meta',hb='name',ib='si.test.Demo::',jb='::',kb='gwt:property',lb='content',mb='=',nb='gwt:onPropertyErrorFn',ob='Bad handler "',pb='" for "gwt:onPropertyErrorFn"',qb='gwt:onLoadErrorFn',rb='" for "gwt:onLoadErrorFn"',sb='/si.test.Demo.nocache.js',tb='Unable to load Super Dev Mode version of si.test.Demo.',ub='selectingPermutation',vb='si.test.Demo.devmode.js',wb='F43A1D087CDC4C886AADF7F2E5B6711E',xb=':',yb=10,zb='.cache.js',Ab='link',Bb='rel',Cb='stylesheet',Db='href',Eb='head',Fb='loadExternalRefs',Gb='gwt/standard/standard.css',Hb='end';var n=window;var o=document;q(H,I);function p(){var a=n.location.search;return a.indexOf(J)!=-1||a.indexOf(K)!=-1}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:L,sessionId:n.__gwtStatsSessionId,subSystem:M,evtGroup:a,millis:(new Date).getTime(),type:b})}}
si_test_Demo.__sendStats=q;si_test_Demo.__moduleName=L;si_test_Demo.__errFn=null;si_test_Demo.__moduleBase=N;si_test_Demo.__softPermutationId=O;si_test_Demo.__computePropValue=null;si_test_Demo.__getPropMap=null;si_test_Demo.__installRunAsyncCode=function(){};si_test_Demo.__gwtStartLoadingFragment=function(){return null};si_test_Demo.__gwt_isKnownPropertyValue=function(){return false};si_test_Demo.__gwt_getMetaProperty=function(){return null};var r=null;var s=n.__gwt_activeModules=n.__gwt_activeModules||{};s[L]={moduleName:L};si_test_Demo.__moduleStartupDone=function(e){var f=s[L].bindings;s[L].bindings=function(){var a=f?f():{};var b=e[si_test_Demo.__softPermutationId];for(var c=O;c<b.length;c++){var d=b[c];a[d[O]]=d[P]}return a}};var t;function u(){v();return t}
function v(){if(t){return}var a=o.createElement(Q);a.src=R;a.id=L;a.style.cssText=S+T;a.tabIndex=-1;o.body.appendChild(a);t=a.contentDocument;if(!t){t=a.contentWindow.document}t.open();var b=document.compatMode==U?V:W;t.write(b+X);t.close()}
function w(f){function g(a){function b(){if(typeof o.readyState==Y){return typeof o.body!=Y&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(o.removeEventListener){o.removeEventListener(Z,d,false)}if(e){clearInterval(e)}}}
if(o.addEventListener){o.addEventListener(Z,d,false)}var e=setInterval(function(){if(b()){d()}},$)}
function h(a){var b=u();var c=b.body;var d=b.createElement(_);d.language=ab;d.src=a;if(si_test_Demo.__errFn){d.onerror=function(){si_test_Demo.__errFn(bb,new Error(cb+a))}}c.appendChild(d);q(db,eb)}
q(db,fb);g(function(){h(f)})}
si_test_Demo.__startLoadingFragment=function(a){return C(a)};si_test_Demo.__installRunAsyncCode=function(a){var b=u();var c=b.body;var d=b.createElement(_);d.language=ab;d.text=a;c.appendChild(d);c.removeChild(d)};function A(){var c={};var d;var e;var f=o.getElementsByTagName(gb);for(var g=O,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(hb),k;if(j){j=j.replace(ib,W);if(j.indexOf(jb)>=O){continue}if(j==kb){k=i.getAttribute(lb);if(k){var l,m=k.indexOf(mb);if(m>=O){j=k.substring(O,m);l=k.substring(m+P)}else{j=k;l=W}c[j]=l}}else if(j==nb){k=i.getAttribute(lb);if(k){try{d=eval(k)}catch(a){alert(ob+k+pb)}}}else if(j==qb){k=i.getAttribute(lb);if(k){try{e=eval(k)}catch(a){alert(ob+k+rb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};r=d;si_test_Demo.__errFn=e}
function B(){n.__gwt_activeModules[L].superdevmode=true;var a=sb;var b=o.getElementsByTagName(_);for(var c=O;;c++){var d=b[c];if(!d){break}var e=d.src;var f=e.lastIndexOf(a);if(f==e.length-a.length){return e.substring(O,f+P)}}n.alert(tb);return null}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return si_test_Demo.__moduleBase+a}
function D(){var f=[];var g=O;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(r){r(a,d,b)}throw null}
__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};si_test_Demo.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};si_test_Demo.__computePropValue=j;n.__gwt_activeModules[L].bindings=si_test_Demo.__getPropMap;q(H,ub);if(p()){return C(vb)}var k;try{k=wb;var l=k.indexOf(xb);if(l!=-1){g=parseInt(k.substring(l+P),yb);k=k.substring(O,l)}}catch(a){}si_test_Demo.__softPermutationId=g;return C(k+zb)}
function F(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=o.createElement(Ab);b.setAttribute(Bb,Cb);b.setAttribute(Db,C(a));o.getElementsByTagName(Eb)[O].appendChild(b);__gwt_stylesLoaded[a]=true}}
q(Fb,I);c(Gb);q(Fb,Hb)}
A();si_test_Demo.__moduleBase=B();s[L].moduleBase=si_test_Demo.__moduleBase;var G=D();F();q(H,Hb);w(G);return true}
si_test_Demo.succeeded=si_test_Demo();